# Override for pulling prebuilt images from GHCR.
# Use with: docker compose -f docker-compose.yml -f docker-compose.ghcr.yml up -d
services:
  garage-init:
    image: "ghcr.io/u1805/mew/garage-init:latest"
    build: null

  server:
    image: "ghcr.io/u1805/mew/server:latest"
    build: null

  client:
    image: "ghcr.io/u1805/mew/client:latest"
    build: null

  plugins:
    image: "ghcr.io/u1805/mew/plugins:latest"
    build: null
